version: 0.0
os: linux
files:
 - source: /scripts/codedeploy_after_install.sh
   destination: /var/
hooks:
  BeforeInstall:
    - location: scripts/codedeploy_before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/codedeploy_after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/codedeploy_start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/codedeploy_stop_server.sh
      timeout: 300
      runas: root
