version: 0.0
os: linux
files:
# If source refers to a directory, then all files (and only files, not directories) 
# in the directory are copied to the instance.
# Ref: https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-files.html
 - source: /myapp.zip
   destination: /var  
hooks:
  BeforeInstall:
    - location: scripts/codedeploy_scripts/codedeploy_before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/codedeploy_scripts/codedeploy_after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/codedeploy_scripts/codedeploy_start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/codedeploy_scripts/codedeploy_stop_server.sh
      timeout: 300
      runas: root
