# for use by AWS CodeBuild service
# Syntax ref: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

env:
  variables:
    ENV_TEST_VAR: "A"

phases:
  install:
    runtime-versions:
      python: 3.9
    on-failure: ABORT       
    commands:
      - echo "Install Phase - $(which python3)"
  pre_build:
    on-failure: ABORT     
    commands:
      - echo Execution started on `date`
  build:
    on-failure: ABORT   
    commands:
      - sh build.sh
  post_build:
    on-failure: CONTINUE   
    commands:
      - echo Execution completed on `date`
# Ref: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec.artifacts
artifacts:
  files:
    - myapp.zip
    # my-subdirectory/**/* represents all files recursively starting from a subdirectory named my-subdirectory.
    - scripts/**/*
    - appspec.yml
    # buildspec.yml - need only in source repo, not in Artifact, since its used
    # only for build & not deployment(deployment - build artifact is used)
